### PR TITLE
Minor updates

### PR DESCRIPTION
**Pull request by titus08**

### CODE REVIEW

**Comment by titus08** [comment]
What kind conflicts are in branch?

**Comment by gubatron** [comment]
a lot of the project structure changed this after noon, please do this:

while standing on your branch
```
git fetch https://github.com/frostwire/frostwire-desktop master
git rebase https://github.com/frostwire/frostwire-desktop master
git push https://github.com/titus08 my-language-update-2015
```

**Comment by titus08** [comment]
I encountered this error:

k1404@k1404-System:~/frostwire-desktop$ git fetch https://github.com/frostwire/frostwire-desktop master
remote: Counting objects: 4746, done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 4746 (delta 1649), reused 1630 (delta 1630), pack-reused 3064
Receiving objects: 100% (4746/4746), 93.29 MiB | 5.63 MiB/s, done.
Resolving deltas: 100% (2910/2910), completed with 295 local objects.
From https://github.com/frostwire/frostwire-desktop
 * branch            master     -> FETCH_HEAD
k1404@k1404-System:~/frostwire-desktop$ git rebase https://github.com/frostwire/frostwire-desktop master
fatal: Needed a single revision
invalid upstream https://github.com/frostwire/frostwire-desktop
k1404@k1404-System:~/frostwire-desktop$ git push https://github.com/titus08 my-language-update-2015
fatal: repository 'https://github.com/titus08/' not found
k1404@k1404-System:~/frostwire-desktop$

What I have to do?

**Comment by titus08** [comment]
k1404@k1404-System:~/frostwire-desktop$ git fetch https://github.com/frostwire/frostwire-desktop master
remote: Counting objects: 4746, done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 4746 (delta 1649), reused 1630 (delta 1630), pack-reused 3064
Receiving objects: 100% (4746/4746), 93.29 MiB | 5.63 MiB/s, done.
Resolving deltas: 100% (2910/2910), completed with 295 local objects.
From https://github.com/frostwire/frostwire-desktop
 * branch            master     -> FETCH_HEAD

k1404@k1404-System:~/frostwire-desktop$ git rebase https://github.com/frostwire/frostwire-desktop master
fatal: Needed a single revision
invalid upstream https://github.com/frostwire/frostwire-desktop

k1404@k1404-System:~/frostwire-desktop$ git push https://github.com/titus08 my-language-update-2015
fatal: repository 'https://github.com/titus08/' not found

k1404@k1404-System:~/frostwire-desktop$

**Comment by gubatron** [comment]
can you please do this for me and paste the output:

`git remote -v`

**Comment by gubatron** [comment]
also you have an error here:

```
git push https://github.com/titus08 my-language-update-2015
fatal: repository 'https://github.com/titus08/' not found
```

it should be:

```
git push https://github.com/titus08/frostwire-desktop my-language-update-2015
```

You missed the name of the repo on the URL.

I asked you about `git remote -v` so that we can use the aliases you have for the remote locations.

I usually have the original repository under `origin`, and my fork under my username.

Like this:
```
$ git remote -v
origin	https://github.com/frostwire/frostwire-desktop.git (push)
origin	https://github.com/frostwire/frostwire-desktop.git (fetch)
gubatron	https://github.com/gubatron/frostwire-desktop.git (push)
gubatron	https://github.com/gubatron/frostwire-desktop.git (fetch)
titus08	https://github.com/titus08/frostwire-desktop.git (push)
titus08	https://github.com/titus08/frostwire-desktop.git (fetch)
```

Then that way commands get a lot easier, you'd do this instead:
`git push titus08 my-language-update-2015`

The beauty of distributed repos.

**Comment by titus08** [comment]
k1404@k1404-System:~/frostwire-desktop$ git init
Reinitialized existing Git repository in /home/k1404/frostwire-desktop/.git/

k1404@k1404-System:~/frostwire-desktop$ git remote -v
origin  http://github.com/titus08/frostwire-desktop (fetch)
origin  http://github.com/titus08/frostwire-desktop (push)

k1404@k1404-System:~/frostwire-desktop$

**Comment by titus08** [comment]
k1404@k1404-System:~/frostwire-desktop$ git init
Reinitialized existing Git repository in /home/k1404/frostwire-desktop/.git/

k1404@k1404-System:~/frostwire-desktop$ git fetch https://github.com/frostwire/frostwire-desktop master
From https://github.com/frostwire/frostwire-desktop
 * branch            master     -> FETCH_HEAD

k1404@k1404-System:~/frostwire-desktop$ git rebase https://github.com/frostwire/frostwire-desktop master
fatal: Needed a single revision
invalid upstream https://github.com/frostwire/frostwire-desktop

k1404@k1404-System:~/frostwire-desktop$ git push https://github.com/titus08/frostwire-desktop my-language-update-2015
Username for 'https://github.com': titus08
Password for 'https://titus08@github.com': 
error: src refspec my-language-update-2015 does not match any.
error: failed to push some refs to 'https://github.com/titus08/frostwire-desktop'

k1404@k1404-System:~/frostwire-desktop$

**Comment by gubatron** [comment]
```
k1404@k1404-System:~/frostwire-desktop$ git remote -v
origin http://github.com/titus08/frostwire-desktop (fetch)
origin http://github.com/titus08/frostwire-desktop (push)
```
Ok, so your origin, is your own fork. Let's change tha by doing the following:

```
git remote rename origin titus08
git remote add origin https://github.com/frostwire/frostwire-desktop
```

after that, just send me the output of `git remote -v` to make sure it's  like it's supposed to.

then we'll just do:

```
git checkout my-language-update-2015
git rebase origin master
```

**Comment by titus08** [comment]
k1404@k1404-System:~/frostwire-desktop$ git init
Reinitialized existing Git repository in /home/k1404/frostwire-desktop/.git/

k1404@k1404-System:~/frostwire-desktop$ git remote rename origin titus08

k1404@k1404-System:~/frostwire-desktop$ git remote add origin https://github.com/frostwire/frostwire-desktop

k1404@k1404-System:~/frostwire-desktop$ git remote -v
origin  https://github.com/frostwire/frostwire-desktop (fetch)
origin  https://github.com/frostwire/frostwire-desktop (push)
titus08 http://github.com/titus08/frostwire-desktop (fetch)
titus08 http://github.com/titus08/frostwire-desktop (push)

k1404@k1404-System:~/frostwire-desktop$

**Comment by titus08** [comment]
k1404@k1404-System:~/frostwire-desktop$ git checkout my-language-update-2015
Branch my-language-update-2015 set up to track remote branch my-language-update-2015 from titus08.
Switched to a new branch 'my-language-update-2015'

k1404@k1404-System:~/frostwire-desktop$ git rebase origin master
fatal: Needed a single revision
invalid upstream origin

k1404@k1404-System:~/frostwire-desktop$

**Comment by gubatron** [comment]
can you type:
`git branch`

and paste the output

**Comment by gubatron** [comment]
or probably much better, give me access to write on your repository and I'll fix it so we can merge this.

**Comment by gubatron** [comment]
also, that error "Invalid upstream origin" might be just a matter of fetching the contents of origin.

`git fetch origin`

**Comment by titus08** [comment]
k1404@k1404-System:~/frostwire-desktop$ git branch
* master
  my-language-update-2015

k1404@k1404-System:~/frostwire-desktop$ git fetch origin
remote: Counting objects: 4807, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 4807 (delta 1655), reused 1651 (delta 1651), pack-reused 3142
Receiving objects: 100% (4807/4807), 94.74 MiB | 9.38 MiB/s, done.
Resolving deltas: 100% (2963/2963), completed with 296 local objects.
From https://github.com/frostwire/frostwire-desktop
 * [new branch]      fw-5-master -> origin/fw-5-master
 * [new branch]      fw4-default -> origin/fw4-default
 * [new branch]      master     -> origin/master
 * [new tag]         6.0.7-build-3 -> 6.0.7-build-3
 * [new tag]         6.0.7-build-4 -> 6.0.7-build-4
 * [new tag]         6.1.1-build-1 -> 6.1.1-build-1
 * [new tag]         6.1.2-build-2 -> 6.1.2-build-2
 * [new tag]         6.1.3-build-2 -> 6.1.3-build-2
 * [new tag]         6.1.3-build-3 -> 6.1.3-build-3
 * [new tag]         frostwire-6.0.6-build-1 -> frostwire-6.0.6-build-1
 * [new tag]         frostwire-6.0.8-build-1 -> frostwire-6.0.8-build-1
 * [new tag]         frostwire-6.1.4-build-2 -> frostwire-6.1.4-build-2
 * [new tag]         frostwire-6.1.5-build-2 -> frostwire-6.1.5-build-2

k1404@k1404-System:~/frostwire-desktop$ 


titus08
asdfghjkl11
Be very carefully do not affect the other git repos in any way. You have 2 days from now. After that I will change the password.

**Comment by gubatron** [comment]
please don't posst your account credentials.
All you have to do is go to the "Settings" of your repository and add "gubatron" as a collaborator.

**Comment by gubatron** [comment]
I'll just grab this branch, rebase this and send a new pull request, don't worry.

**Pull request closed without merging**
