### PR TITLE
Delete ro.po

### PR DESCRIPTION
**Pull request by titus08**

### CODE REVIEW

**Comment by gubatron** [comment]
why?

**Comment by titus08** [comment]
I translate FrostWire in Romanian, but GIT is not friendly to me. Still now I try to make a pull request but something goes wrong. Maybe you can give me some how-know about this problem. I delet the file ro.po from a mistake. See:  https://github.com/titus08/frostwire    https://github.com/titus08/frostwire-desktop/tree/my-language-update-2015

**Comment by titus08** [comment]
I follow all the steps from  http://forum.frostwire.com/viewtopic.php?f=9&t=4922

k1404@Windows10:~/frostwire-desktop$ git push origin my-language-update-2015
Username for 'https://github.com': titus08
Password for 'https://titus08@github.com': 
Total 0 (delta 0), reused 0 (delta 0)
To http://github.com/titus08/frostwire-desktop
 * [new branch]      my-language-update-2015 -> my-language-update-2015
k1404@Windows10:~/frostwire-desktop$ 

But in my  https://github.com/titus08/frostwire-desktop/tree/my-language-update-2015 the file ro.po still is not updated....

**Comment by titus08** [comment]
After a long way of all kinds of mantras and ,,blessings,, I finally did it. I have succeeded to make GIT friendly to me.

**Comment by gubatron** [comment]
let me know then if I should close this pull request

**Comment by titus08** [comment]
Right now I push the final version of ro.po.

**Pull request closed without merging**
