### PR TITLE
Update hr.po

### PR DESCRIPTION
**Pull request by win32re**

### CODE REVIEW

**Comment by gubatron** [comment]
are you changing words back and forth?

**Comment by win32re** [comment]
@gubatron nope, I guess I screwed something up with my git repository. will check this out now

**Comment by win32re** [comment]
yeah, I re-forked the repository and will clean this mess up. should be finished tomorrow

**Comment by gubatron** [comment]
you just need to do `git pull` from the master repo.

I've squashed all these commits and re-uploaded things.

**Pull request merged**
