### PR TITLE
Update hr.po

### PR DESCRIPTION
**Pull request by entity0**

### CODE REVIEW

**Comment by gubatron** [comment]
Please take a look @darthxjanus @X-NicON

**Comment by darthxjanus** [comment]
@gubatron I think you can merge it. Cheers!

**Comment by gubatron** [comment]
just making sure these changes don't revert to a previous state you guys have already fixed.

**Comment by gubatron** [comment]
now waiting for @X-NicON's 2nd LGTM and we're ready to merge.

**Comment by darthxjanus** [comment]
@gubatron OK :) Most of it is new but it's a good idea to wait for Nikita's confirmation.

**Comment by X-NicON** [comment]
And they called me. I`m happy.

https://github.com/frostwire/frostwire-desktop/commit/98641222ffd3b5827dab5939bbfb11b010e53e92#diff-5d72aeda2abfdac38d567e370af81f74L4680
I understand "postavke" word must be present?

And think that after so many commits hr.po finally finished?

**Comment by entity0** [comment]
@X-NicON @gubatron  The word "postavke" is there because without it it would make no sense (you won't be able to know what is the string referring to). Regarding the commits, the translation is mostly done, these are just some small updates/fixes.

**Comment by gubatron** [comment]
is it good then @X-NicON ?

**Comment by X-NicON** [comment]
@gubatron Yes, everything is fine

**Comment by gubatron** [comment]
Thank you everyone!

**Pull request merged**
