### PR TITLE
SystemUtils.java code lines number reduction (3)

### PR DESCRIPTION
**Pull request by abderraouf-adjal**
File `SystemUtils.java` code lines number reduction using `() ? : ` and cleanup.
Use `tabs` to indent, Unfortunately there is no [Coding Guidelines](https://github.com/frostwire/frostwire-desktop#coding-guidelines) rule in the project about what to use.

### CODE REVIEW

**Comment by gubatron** [comment]
LGTM
:+1:

**Comment by gubatron** [comment]
thank you

**Comment by abderraouf-adjal** [comment]
Finally :dancer:

**Comment by gubatron** [comment]
Thanks for not giving up. It's important to get things right, then others won't come and put sloppy code.

**Pull request merged**
